### PR TITLE
Added crash resiliency, refactored Litejobqueue, got test suite consistently passing, and created a helper to simplify and standardize configuration

### LINKED ISSUE #17: Cannot configure Litejobqueue queues
In short, `setup` is called before `@queueus` get's properly setup, meaning that workers are started without queues.

To lay out the story more fully:

Let's imagine you initialize a `Litejobqueue` like so:
```ruby
jobqueue = Litejobqueue.new({
  path: ":memory:",
  retries: 2,
  retry_delay: 1,
  retry_delay_multiplier: 1,
  # gc_sleep_interval: 1,
  # dead_job_retention: 1,
  # logger: 'STDOUT',
  queues: [
    ['test', 1]
  ]
})
```

`Litejobqueue.new` will call https://github.com/oldmoe/litestack/blob/8a061b849f2e3dd137f398fca0fd99a8ea5451c0/lib/litestack/litejobqueue.rb#L60-L65

At line 63 `Litejobqueue#initialize` is called, which will run https://github.com/oldmoe/litestack/blob/8a061b849f2e3dd137f398fca0fd99a8ea5451c0/lib/litestack/litejobqueue.rb#L70-L83

The `super` at line 73 is calling `Litequeue#initialize`, which is simply https://github.com/oldmoe/litestack/blob/8a061b849f2e3dd137f398fca0fd99a8ea5451c0/lib/litestack/litequeue.rb#L39-L41

This `init` method called actually comes from the included `Litesupport::Liteconnection` module and is defined as https://github.com/oldmoe/litestack/blob/8a061b849f2e3dd137f398fca0fd99a8ea5451c0/lib/litestack/litesupport.rb#L277-L290

The `setup` call at line 271 will call the `Litejobqueue#setup` method: https://github.com/oldmoe/litestack/blob/8a061b849f2e3dd137f398fca0fd99a8ea5451c0/lib/litestack/litejobqueue.rb#L157-L163

At line 160 we see the call to `Litejobqueue#create_worker` which will spawn our worker threads/fibers/whatever. 

The issue is that when https://github.com/oldmoe/litestack/blob/8a061b849f2e3dd137f398fca0fd99a8ea5451c0/lib/litestack/litejobqueue.rb#L188 runs and inspects the `@queues` instance variable, we are still within the execution context of `Litejobqueue#initialize` line 73. The `@queues` instance variable won't be populated until line 81.

You can verify this with a simple `puts` in the code.

- - - 

The core pain point here, for me, is that it hinders my ability to set up tests. While I can understand well _why_ this is happening, I am not yet confident in how best to fix things to resolve this issue. Happy to help with some guidance tho.

### LINKED ISSUE #63: How do I run the test suite for this project?
I dont seem to be able to run the test suite for this project. 

- Right away it complains about cannot find `active_record` so I add `gem "rails"` to the Gemfile to get past this
- After that I get more errors coming from `test/test_ar_search.rb` (`unrecognized option: "contentless_delete" (SQLite3::SQLException)`)
- After skipping `test/test_ar_search.rb` then I receive more errors in `test/test_litejob.rb` (`cannot load such file -- ../lib/litestack/litejobqueue`)

Would like to be able to just type `bundle exec rake test` and have the test suite just work. However I cant help out with that until I get some info for steps here.

Can you please provide some instructions on how to run the test suite?

### PR DESCRIPTION
**Pull request by RyanVasichko**
@oldmoe - This PR replaces #66 and handles requeueing dead jobs by considering jobs that have been running for a long time to be dead. An option for jobs to customize their considered dead time is provided with the `considered_dead_after` DSL that can be used in a Job class declaration.

In addition this contains a refactoring that should make Litejobqueue more maintainable by switching from a procedural to object-oriented style. A full suite of tests for these changes are included. And as an added benefit the job tests no longer intermittently fail.

I've also created `LiteSupport::Configurable` which standardizes and simplifies configurations and adds the ability to use a `.configure` block for those that prefer to place their configurations in an initializer. Unit tests for this are also included.

This also closes #63

### CODE REVIEW

**Comment by oldmoe** [comment]
Thanks a lot @RyanVasichko I will review and test this and merge if everything looks good

**Comment by oldmoe** [comment]
I have been reviewing the PR and this change is actually huge, I think we should break it down a bit before we can start applying these changes, there also some notes regarding the code:

- I wouldn't want to move the sql statements from the *.sql.yml files and mix them with the Ruby code, this was intentionally to move them away from Ruby code, having them back is not something I would vote for.
- The whole thing should live under litestack, if a component grows large enough, it can get its own folder under litestack, like with litesearch
- I wouldn't want to have files called lite_job.rb and others called litejob.rb, same for folder names, I would stick to litejob throughout

**Comment by RyanVasichko** [comment]
Thanks for the feedback.

1. I don't believe there is any value in placing the SQL statements in a separate file, and doing so would create a more incoherent code base, something this project already struggles with.

2. Ruby convention is to place a module's classes/sub-modules in their own folder named in snake_case after the parent module

3. Ruby convention is to PascalCase class names and snake_case file names. So it should be LiteJob and lite_job

Thank you for taking the time to review this PR. Unfortunately the changes requested would be detrimental to the readability and maintainability of the code, and also violate well-established Ruby conventions. If there are smaller PRs you would prefer this broken down into due to the scope of the changes please let me know.

**Comment by oldmoe** [comment]
1. I am keen on separating the data layer "SQL" and Ruby as much as possible. My vision is that the *.sql.yml files should represent the bulk of functionality, and more (not less) should go there as more SQLite features get utilized. So no, I don't this makes for a more incoherent code base, at least not that particular aspect.

2. The new design loses the base classes litequeue, and it is a pity since I already use this class in different contexts, it provides basic functionality that is not tied to the Litejob interface, something I don;t want to lose.

3. Regarding the folders, I am not arguing against having sub modules in folders, I am just trying to make sure they are all children of the litestack folder

4. As for the naming convention, I am aware of that, still intentionally using lite* as a single word for all class names rather than something to be broken up by camel case. Appreciate your input but I would stick to the project's original convention regarding class/folder naming.

5. Furthermore, the breakage of functionality into small modules/classes (I know, SOLID, I know) actually makes the code splintered in a lot of files and much harder to grok for someone looking at the codebase for the first time.  

That said, I really appreciate a lot of what went into the PR and appreciate your interest in Litestack (with a small s), so if you would like to approach this differently here is a list of smallish changes that can be useful

1. A separate PR for the configuration changes, allowing for the class.config{ } interface
2. Another PR for tests that use timecop and cover the different functionality aspects of litejob
3. Another PR that implements the crash resilience aspect as we discussed

Since I was planning to do 2 and 3 originally, I am happy to deliver on these anyway, but any help is welcome.

**Pull request closed without merging**
