### PR TITLE
Require Litekd

### PR DESCRIPTION
**Pull request by bopm**
I would like to use it :)

### CODE REVIEW

**Comment by oldmoe** [comment]
It is not ready yet for public consumption! Should be ready by the next
release, until then, you require it individually if you want to try it.

**Comment by bopm** [comment]
I suspected that, but it only will affect someone if that one have module
with same name or will use include Litekb::Attibutes in the model, ain’t it?

**Comment by oldmoe** [comment]
you are actually right, I will merge then, please be aware that there could be bugs.

**Comment by bopm** [comment]
So far so good for unique lists.

**Pull request merged**
